import type { Campaign, Lead } from "@/lib/types";

export const demoLeads: Lead[] = [
  {
    id: "demo-1",
    businessName: "Northline Dental Studio",
    category: "Dentist",
    address: "214 Market Street, Austin, TX",
    phone: "+1 512 555 0182",
    website: "https://northlinedental.example",
    googleMapsUrl: "https://maps.google.com/?q=Northline%20Dental%20Studio",
    rating: 4.8,
    reviewCount: 186,
    location: "Austin, TX",
    country: "United States",
    source: "google_maps",
    aiScore: 92,
    temperature: "Hot",
    status: "new",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    businessName: "Peak Fitness Club",
    category: "Gym",
    address: "88 Lake Avenue, Dallas, TX",
    phone: "+1 214 555 0196",
    website: "https://peakfitness.example",
    googleMapsUrl: "https://maps.google.com/?q=Peak%20Fitness%20Club",
    rating: 4.4,
    reviewCount: 74,
    location: "Dallas, TX",
    country: "United States",
    source: "google_maps",
    aiScore: 78,
    temperature: "Hot",
    status: "new",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    businessName: "Atlas Web Agency",
    category: "Marketing Agency",
    address: "17 King Road, Toronto, ON",
    phone: "+1 416 555 0130",
    website: "https://atlasweb.example",
    googleMapsUrl: "https://maps.google.com/?q=Atlas%20Web%20Agency",
    rating: 4.1,
    reviewCount: 29,
    location: "Toronto, Canada",
    country: "Canada",
    source: "google_maps",
    aiScore: 66,
    temperature: "Warm",
    status: "new",
    createdAt: new Date().toISOString(),
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Local Services Outreach",
    subject: "Quick growth idea for {{company}}",
    template: "Hi {{name}}, I found {{company}} on Google Maps and noticed an opportunity...",
    status: "draft",
    leadCount: 128,
    opens: 0,
    clicks: 0,
    bounces: 0,
    createdAt: new Date().toISOString(),
  },
];
