export const serviceOptions = [
  "SEO Services",
  "Web Design",
  "Paid Ads",
  "Email Marketing",
  "CRM Setup",
  "Lead Generation",
  "Social Media Marketing",
  "Content Marketing",
  "Branding",
  "Graphic Design",
  "Video Production",
  "Copywriting",
  "E-commerce Development",
  "Shopify Development",
  "WordPress Development",
  "Mobile App Development",
  "SaaS Development",
  "AI Automation",
  "Chatbot Development",
  "Cybersecurity",
  "IT Support",
  "Cloud Services",
  "Accounting",
  "Bookkeeping",
  "Business Consulting",
  "HR Services",
  "Recruiting",
  "Virtual Assistant",
  "Customer Support",
  "Call Center",
  "Appointment Setting",
  "Sales Outreach",
  "PR Services",
  "Event Marketing",
  "Local SEO",
  "Reputation Management",
  "Conversion Optimization",
  "Analytics Setup",
  "Data Scraping",
  "Data Enrichment",
];

export const categoryOptions = [
  "Healthcare",
  "Dental",
  "Fitness",
  "Real Estate",
  "Restaurants",
  "Agencies",
  "SaaS",
  "Home Services",
  "Legal Services",
  "Accounting Firms",
  "Insurance",
  "Financial Services",
  "E-commerce",
  "Retail",
  "Beauty Salons",
  "Spas",
  "Clinics",
  "Hospitals",
  "Pharmacies",
  "Chiropractors",
  "Veterinary Clinics",
  "Auto Repair",
  "Car Dealerships",
  "Construction",
  "Roofing",
  "Plumbing",
  "HVAC",
  "Electrical Contractors",
  "Landscaping",
  "Cleaning Services",
  "Moving Companies",
  "Pest Control",
  "Security Services",
  "Education",
  "Schools",
  "Coaching",
  "Recruiting Agencies",
  "Manufacturing",
  "Logistics",
  "Warehousing",
  "Travel Agencies",
  "Hotels",
  "Gyms",
  "Nonprofits",
  "Churches",
  "Software Companies",
  "Marketing Agencies",
  "Consulting Firms",
  "B2B Services",
  "Local Businesses",
];
